name: Update M3U8 Playlist

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install node-fetch@2 winston

      - name: Run Script
        run: node parse.js

      - name: Configure git user
        run: |
          git config --global user.name 'Siva2webdev'
          git config --global user.email "${{ secrets.USER_EMAIL }}"

      - name: Commit and Push Changes
        run: |
          git add play.m3u
          git commit -m 'Update M3U8 playlist'
          git push origin ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.BINDAAS }}
